repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1  # Use the latest stable tag from Ruff's repo
    hooks:
      - id: ruff-check
        args: [--fix]  # Optional: auto-fix issues
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.6"
    hooks:
      - id: bandit
        args: ["--configfile=pyproject.toml", "--recursive", "-a=file"]
