name: PyPI Publish

on:
  release:
    types:
      - published

permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==2.5.1

      - name: Check Poetry version
        run: poetry --version

      - name: Check pyproject.toml validity
        run: poetry check

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1